### ISSUE TITLE
Bug on startup

### ISSUE THREAD

**Issue by middo1** [rubbieKelvin/notes#52]
```

warn @ runtime-core.esm-bundler.js:38
logError @ runtime-core.esm-bundler.js:212
handleError @ runtime-core.esm-bundler.js:204
callWithErrorHandling @ runtime-core.esm-bundler.js:158
setupStatefulComponent @ runtime-core.esm-bundler.js:7109
setupComponent @ runtime-core.esm-bundler.js:7064
mountComponent @ runtime-core.esm-bundler.js:4951
processComponent @ runtime-core.esm-bundler.js:4926
patch @ runtime-core.esm-bundler.js:4518
mountChildren @ runtime-core.esm-bundler.js:4714
mountElement @ runtime-core.esm-bundler.js:4623
processElement @ runtime-core.esm-bundler.js:4595
patch @ runtime-core.esm-bundler.js:4515
componentUpdateFn @ runtime-core.esm-bundler.js:5066
run @ reactivity.esm-bundler.js:185
setupRenderEffect @ runtime-core.esm-bundler.js:5185
mountComponent @ runtime-core.esm-bundler.js:4968
processComponent @ runtime-core.esm-bundler.js:4926
patch @ runtime-core.esm-bundler.js:4518
mountChildren @ runtime-core.esm-bundler.js:4714
mountElement @ runtime-core.esm-bundler.js:4623
processElement @ runtime-core.esm-bundler.js:4595
patch @ runtime-core.esm-bundler.js:4515
componentUpdateFn @ runtime-core.esm-bundler.js:5066
run @ reactivity.esm-bundler.js:185
setupRenderEffect @ runtime-core.esm-bundler.js:5185
mountComponent @ runtime-core.esm-bundler.js:4968
processComponent @ runtime-core.esm-bundler.js:4926
patch @ runtime-core.esm-bundler.js:4518
componentUpdateFn @ runtime-core.esm-bundler.js:5066
run @ reactivity.esm-bundler.js:185
setupRenderEffect @ runtime-core.esm-bundler.js:5185
mountComponent @ runtime-core.esm-bundler.js:4968
processComponent @ runtime-core.esm-bundler.js:4926
patch @ runtime-core.esm-bundler.js:4518
mountChildren @ runtime-core.esm-bundler.js:4714
mountElement @ runtime-core.esm-bundler.js:4623
processElement @ runtime-core.esm-bundler.js:4595
patch @ runtime-core.esm-bundler.js:4515
mountChildren @ runtime-core.esm-bundler.js:4714
mountElement @ runtime-core.esm-bundler.js:4623
processElement @ runtime-core.esm-bundler.js:4595
patch @ runtime-core.esm-bundler.js:4515
mountChildren @ runtime-core.esm-bundler.js:4714
mountElement @ runtime-core.esm-bundler.js:4623
processElement @ runtime-core.esm-bundler.js:4595
patch @ runtime-core.esm-bundler.js:4515
componentUpdateFn @ runtime-core.esm-bundler.js:5066
run @ reactivity.esm-bundler.js:185
setupRenderEffect @ runtime-core.esm-bundler.js:5185
mountComponent @ runtime-core.esm-bundler.js:4968
processComponent @ runtime-core.esm-bundler.js:4926
patch @ runtime-core.esm-bundler.js:4518
componentUpdateFn @ runtime-core.esm-bundler.js:5136
run @ reactivity.esm-bundler.js:185
callWithErrorHandling @ runtime-core.esm-bundler.js:155
flushJobs @ runtime-core.esm-bundler.js:394
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:285
queueCb @ runtime-core.esm-bundler.js:307
queuePostFlushCb @ runtime-core.esm-bundler.js:313
queueEffectWithSuspense @ runtime-core.esm-bundler.js:1579
scheduler @ runtime-core.esm-bundler.js:1801
triggerEffects @ reactivity.esm-bundler.js:382
triggerRefValue @ reactivity.esm-bundler.js:982
(anonymous) @ reactivity.esm-bundler.js:1113
triggerEffects @ reactivity.esm-bundler.js:382
triggerRefValue @ reactivity.esm-bundler.js:982
(anonymous) @ reactivity.esm-bundler.js:1113
triggerEffects @ reactivity.esm-bundler.js:382
triggerRefValue @ reactivity.esm-bundler.js:982
set value @ reactivity.esm-bundler.js:1026
finalizeNavigation @ vue-router.esm-bundler.js:3194
(anonymous) @ vue-router.esm-bundler.js:3067
Promise.then (async)
pushWithRedirect @ vue-router.esm-bundler.js:3038
push @ vue-router.esm-bundler.js:2966
install @ vue-router.esm-bundler.js:3380
use @ runtime-core.esm-bundler.js:3834
(anonymous) @ main.js:14
Show 27 more frames
runtime-core.esm-bundler.js:38 [Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core 
  at <ComboBox list= (4) ['DEFAULT', 'ALPHABETICAL', 'DATE_CREATED', 'DATE_EDITED'] getDefault=fn<getDefault> getItemText=fn<getItemText>  ... > 
  at <NoteSearch onUpdate:searchtext=fn<setSearch> > 
  at <Notes onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <Index class="text-base" onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView class="text-base" > 
  at <App>
warn @ runtime-core.esm-bundler.js:38
logError @ runtime-core.esm-bundler.js:212
handleError @ runtime-core.esm-bundler.js:204
callWithErrorHandling @ runtime-core.esm-bundler.js:158
flushJobs @ runtime-core.esm-bundler.js:394
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:285
queueCb @ runtime-core.esm-bundler.js:307
queuePostFlushCb @ runtime-core.esm-bundler.js:313
queueEffectWithSuspense @ runtime-core.esm-bundler.js:1579
scheduler @ runtime-core.esm-bundler.js:1801
triggerEffects @ reactivity.esm-bundler.js:382
triggerRefValue @ reactivity.esm-bundler.js:982
(anonymous) @ reactivity.esm-bundler.js:1113
triggerEffects @ reactivity.esm-bundler.js:382
triggerRefValue @ reactivity.esm-bundler.js:982
(anonymous) @ reactivity.esm-bundler.js:1113
triggerEffects @ reactivity.esm-bundler.js:382
triggerRefValue @ reactivity.esm-bundler.js:982
set value @ reactivity.esm-bundler.js:1026
finalizeNavigation @ vue-router.esm-bundler.js:3194
(anonymous) @ vue-router.esm-bundler.js:3067
Promise.then (async)
pushWithRedirect @ vue-router.esm-bundler.js:3038
push @ vue-router.esm-bundler.js:2966
install @ vue-router.esm-bundler.js:3380
use @ runtime-core.esm-bundler.js:3834
(anonymous) @ main.js:14
NoteSearch.vue:15 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'replace')
    at Proxy.getItemText (NoteSearch.vue:15:30)
    at setup (ComboBox.vue:50:13)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7109:29)
    at setupComponent (runtime-core.esm-bundler.js:7064:11)
    at mountComponent (runtime-core.esm-bundler.js:4951:13)
    at processComponent (runtime-core.esm-bundler.js:4926:17)
    at patch (runtime-core.esm-bundler.js:4518:21)
    at mountChildren (runtime-core.esm-bundler.js:4714:13)
    at mountElement (runtime-core.esm-bundler.js:4623:17)
```

```html
<ComboBox
      :list="sortingOptions"
      :getDefault="() => savedItem"
      :getItemText="(i) => i.replace('_', ' ')"
      @selected="updateSortingSetting"
      v-slot="{ open, selectedText }"
    >
```

Error was gotten after clearing application data

**Comment by middo1** [comment]
![image](https://user-images.githubusercontent.com/56052889/168284636-b6d7cd17-c3ce-46df-8549-c29ac4f91716.png)

**Comment by rubbieKelvin** [comment]
[localhost-1652470915914.log](https://github.com/rubbieKelvin/notes/files/8690922/localhost-1652470915914.log)
this is the log output for the bug in my browser

**Comment by rubbieKelvin** [comment]
i fixed the bug relating to this:
![image](https://user-images.githubusercontent.com/46853759/168395347-d3e8eb85-4e4b-4ce3-802f-655829a76f54.png)

**Comment by middo1** [comment]
Nice
